### ISSUE TITLE
[Infrastructure] Backup argilla databases

### ISSUE THREAD

**Issue by PaulNdrei** [langtech-bsc/argilla-eval#3]
To Argilla deployment to be production ready it need to implement some backup system.

To backup:
 - Postgres SQL database
 - ElasticSearch indices.

**Comment by PaulNdrei** [comment]
I have already implemented a backup system for both database engines.

For Postgres: https://github.com/eeshugerman/postgres-backup-s3
For ElasticSearch, i have created a fork of `eeshugerman/postgres-backup-s3` and adapted it to the need of backuping the multiples indices that Argilla stores.

The fork:  https://github.com/langtech-bsc/multi-elasticsearch-backup-s3

Both backup systems are directly integrated into the deployment file (docker-compose)

**Comment by gullabi** [comment]
I understand that this is implemented. We might need more info in its implementation in our infra, but closing it for now.
